name: Run Python unittests

on:
  push:
    branches:
      - '**'  # Ejecuta en todos los branches al hacer push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Cambia la versión según tu proyecto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Ignora si no existe

      - name: Run unittests
        run: |
          python -m unittest discover -s tests

